name: CI/CD Process
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
      || startsWith(github.head_ref, 'dependabot/')
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      
      - uses: actions/checkout@v4
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - run: ./architect init

      - name: Release
        run: |
          zip -r executable/semantic-release.zip executable
          cp -r plugin/build/libs/architect-semantic-release-0.1-all.jar executable/semantic-release-plugin.jar
          cd executable && ./release
          
